Update item_effects.h pipup
removed the EV_berry_friendship_change from Pipup, since it doesnt have an add ev part?

In file included from src/item.c:30:
src/data/pokemon/item_effects.h:473:25: error: array index in initializer exceeds array bounds
  473 |     EV_BERRY_FRIENDSHIP_CHANGE,
      |                         ^
src/data/pokemon/item_effects.h:473:25: note: (near initialization for 'gItemEffect_PipupBerry')
src/data/pokemon/item_effects.h:473:30: error: excess elements in array initializer [-Werror]
  473 |     EV_BERRY_FRIENDSHIP_CHANGE,
      |                              ^
src/data/pokemon/item_effects.h:473:30: note: (near initialization for 'gItemEffect_PipupBerry')